# Generated by Django 5.1.5 on 2025-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiorecording',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='audiorecording',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='duration',
            field=models.FloatField(default=5.0),
        ),
    ]
