# Generated by Django 5.1.5 on 2025-02-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0003_audiorecording_analysis_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('speaker_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='audiorecording',
            name='recorder_au_usernam_60e06d_idx',
        ),
        migrations.RemoveIndex(
            model_name='audiorecording',
            name='recorder_au_is_anal_833f3c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='audiorecording',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='clip_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='duration',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='analysis_timestamp',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='is_analyzed',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='max_amplitude',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_amplitude',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_mfcc',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_rms_energy',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_spectral_centroid',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_spectral_rolloff',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='mean_zero_crossing_rate',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='min_amplitude',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='tempo',
        ),
    ]
