# Generated by Django 5.1.5 on 2025-02-04 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speaker_number',
            field=models.IntegerField(unique=True),
        ),
    ]
